### PR TITLE
Tutorials

### PR DESCRIPTION
**Pull request by jakobkolb**
Created Tutorial explaining the usage of MPI with IPython notebooks and mpi4py. Please test, if the desired results are replicable with the described procedure.

### CODE REVIEW

**Comment by jakobkolb** [comment]
Resaving seems to work in the tutorial notebook. Curiously, the resaving method does not seem to save the results into a file though.

**Comment by wbarfuss** [comment]
Thanks Jakob, looks great!

Some comments:
- we should rename the tutorials
  - `01_tutorial.ipynb` --> `01_RunningAModel.ipynb`
  - `02_tutorial.ipynb` --> `02_LocalParallelization.ipynb`
  - `02_tutorial.ipynb` --> `02_EsembleEvaluation.ipynb`
  or with better names
- updating unit tests at https://github.com/wbarfuss/pymofa/blob/master/tests/test_tutorial.py#L54
  and make sure all notebooks pass
- Resaving
  What is the issue here exactly? This needs to be resolved.

**Comment by jakobkolb** [comment]
I fixed some issues:

* The resaving method just wasn't saving its results... Now it does,
* I renamed the tutorial files,
* I updated the unit tests to start an ipcluster in order to be able to test parallelized notebooks,
* I included the new tutorial notebooks in the list of notebooks to test,
* I adjusted some things here and there to make the unit tests pass (except for some pep 257 issues that are save to ignore from where I stand)

Does this satisfy the maintainer ? ;)

**Comment by wbarfuss** [comment]
Thanks a lot! But where is your `tutorial` folder in your `tutorials` branch?

**Comment by jakobkolb** [comment]
Actually added the tutorials folder and fixed a bug, I found.
(For non-dataframe data, the index of the resulting dataframe was not ordered correctly.)

**Pull request merged**
